- hosts: all
  gather_facts: no
  remote_user: root

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip

  tasks:

    - name: create environment variables from template
      template:
        src: environment.j2
        dest: '.env'

    - name: run container
      community.docker.docker_container:
        name: redmine-app
        image: redmine
        published_ports: 80:3000
        restart_policy: always
        restart: yes
        container_default_behavior: no_defaults
        pull: yes
        env_file: .env
