datadog_site: 'datadoghq.eu'
datadog_api_key: {{ datadog_api_key }}
datadog_checks:
    http_check:
        init_config:
        instances:
            - name: app_healthcheck
              url: http://localhost:80
              timeout: 5
              method: GET
